version: '3.3'
services:
  mongo:
    image: mongo:4.2.5
  backend:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'
  frontend:
    build: ./Frontend/312client
    ports:
    - '8081:8080'
    depends_on:
      - backend
